apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: minha-app-pod-monitor
  namespace: monitoring
  labels:
    release: monitoramento
spec:
  # Esta linha permite encontrakubectl apply -f k8s/pod-monitor-videos.yamlr a app mesmo que esteja em namespaces diferentes (ex: default)
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app: minha-app-clientes
  podMetricsEndpoints:
    - targetPort: 8080
      path: /actuator/prometheus
      interval: 15s